---
kind: pipeline
name: default

steps:
  - name: Test apllication
    image: node:12.13.1
    commands:
      - yarn install
      - yarn lint
      - yarn test || echo tests are not ok

  - name: "Bump & Tag"
    image: quay.io/openware/sdk-citools:2.3.1
    environment:
      BRANCH_NAME: ${DRONE_BRANCH}
      REPO_NAME: ${DRONE_REPO}
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:prebuild

  - name: Republish package on npmjs
    image: node:12.13.1
    environment:
      NPM_LOGIN:
        from_secret: npmjs_login
      NPM_PASS:
        from_secret: npmjs_pass
      NPMJS_TOKEN:
        from_secret: npmjs_token
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - git config --global user.name "kite-bot"
      - git config --global user.email "kite-bot@heliostech.fr"
      - git remote set-url origin https://kite-bot:$GITHUB_API_KEY@github.com/${DRONE_REPO}
      - git fetch origin
      - echo "//registry.npmjs.org/:_authToken=$NPMJS_TOKEN" > .npmrc
      - npm --no-git-tag-version version "$(cat VERSION)"
      - npm publish --access=public | true
      - git add package.json VERSION
      - git commit --amend -m "$(git log -1 --pretty) [CI SKIP]"
      - git tag $(cat VERSION) | true
      - git push -f origin ${DRONE_BRANCH} | true
      - git push --tags origin | true
      - git describe --tags $(git rev-list --tags --max-count=1) > .tags
    when:
      event:
        - push

trigger:
  event:
  - push

image_pull_secrets:
  - dockerconfigjson

