---
kind: pipeline
name: default

steps:
  - name: Test apllication
    image: node:12.13.1
    commands:
      - yarn install
      - yarn lint
      - yarn test || echo tests are not ok

  - name: Republish package on npmjs
    image: node:12.13.1
    environment:
      REPO_NAME: ${DRONE_REPO}
      NPM_LOGIN:
        from_secret: npmjs_login
      NPM_PASS:
        from_secret: npmjs_pass
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - git config --global user.name "kite-bot"
      - git config --global user.email "kite-bot@heliostech.fr"
      - git remote add authenticated-origin https://kite-bot:$GITHUB_API_KEY@github.com/${DRONE_REPO}
      - git fetch
      - sh scripts/version_bump.sh $NPM_LOGIN $NPM_PASS
      - git add package.json
      - git commit --amend --no-edit

  - name: Version Tag
    image: quay.io/openware/sdk-citools:2.3.1
    environment:
      BOT_USERNAME: kite-bot
      BOT_NAME: Kite Bot
      BOT_EMAIL: kite-bot@heliostech.fr
      BRANCH_NAME: ${DRONE_BRANCH}
      REPO_NAME: ${DRONE_REPO}
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - BUNDLE_GEMFILE=f/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:prebuild


trigger:
  branch:
  - master
  event:
  - push

image_pull_secrets:
  - dockerconfigjson

